import express from "express";
import { getOrderByTableId, createOrder, deleteOrder, finishOrder, declineOrder, completeOrder, startOrder, cancelOrder } from "../controllers/order.js";
const router = express.Router();
router.get('/:tableId', getOrderByTableId);
router.post('/create', createOrder);
router.post('/delete', deleteOrder);
router.post('/cancel', cancelOrder);
router.post('/finish', finishOrder);
router.post('/decline', declineOrder);
router.post('/start', startOrder);
router.post('/complete', completeOrder);
export default router;
